version: "3.7"

services:
  db:
    build: .
    restart: always
    ports:
      - 33086:3306
    environment:
      - MYSQL_ROOT_PASSWORD=itMustBeAVeryStrongPassword
      - MYSQL_DATABASE=biblio
      - MYSQL_USER=biblio
      - MYSQL_PASSWORD=biblio

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8889:80
    environment:
      - PMA_ARBITRARY=1

